### ISSUE TITLE
Chinitsu toitoi sanankou not recognized

### ISSUE THREAD

**Issue by phantomics** [pwmarcz/minefield#47]
See the attached image. The game begins, I'm dealt an amazing selection of tiles, and I build a chinitsu toitoi sanankou hand. The bot deals into my wait on the second turn and... nothing. It deals into the other half of my wait the next turn and double nothing. What's going on here?

I'm guessing there's some issue with the way you prioritize registering straights and triples. The program may recognize `4 4 5 5 5 6 6 6` as two complete `4 5 6` straights and an incomplete `5 6` rather than as two triples of 5 and 6 and a pair of 4s.

![MinefieldBugShot](https://github.com/pwmarcz/minefield/assets/4529456/f210b626-9ec2-4230-95d7-61e67529640a)

**Comment by monoidal** [comment]
You've started by dealing 1m, which is one of your waits. Therefore you're in furiten.

Per docs:
> Watch out for furiten! Unfortunately, it applies even if either you or your opponent deals one of your cheaper (that is, non-mangan) waits.

**Comment by phantomics** [comment]
You're right, I was careless about dealing that 1m. I was so focused on the toitoi I didn't even think how that series could become a bunch of interwoven manzu runs.
